---
title: "Advanced Dashboarding"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    social: ["menu"]
    source_code: embed
    theme: 
      version: 4
      bootswatch: sandstone
---

<!-- see also bootswatch for themes -->

```{r setup, include=FALSE}
# From: https://www.youtube.com/watch?v=Opa_Nf88mCU

library(flexdashboard)
library(tidyverse)
library(palmerpenguins)
library(plotly)
library(DT)
library(fontawesome)
data ("penguins")

```

Plot {data-navmenu="Pages"}
======================================================================
Sidebar {.sidebar}
-----------------------------------------------------------------------
### Penguin Stats

There are `r nrow(penguins)` observations in the dataset.  

Row 
-----------------------------------------------------------------------
### Number of Penguins

```{r}
# fontawesome has thousands of free icons
valueBox(nrow(penguins), icon = "fa-linux")

```


Row {.tabset}
-----------------------------------------------------------------------

### Scatterplot of Penguin Bill Length vs Bill Depth

```{r}
splot <- penguins |> 
  ggplot (aes (x = bill_length_mm, y = bill_depth_mm, color = species)) + 
  geom_point()

ggplotly(splot)
```


### Boxplot of Body Mass

```{r}
penguins |> 
  ggplot (aes(x = body_mass_g, y = sex, fill = sex)) + 
  geom_boxplot()
```

Row 
------------------------------------------------------------------------
### Histogram of Flipper Length

```{r}
penguins |> 
  ggplot (aes(x = flipper_length_mm, fill = species)) + 
  geom_histogram() + 
  facet_wrap(~species)
```

Data {data-navmenu="Pages"}
========================================================================

```{r}
penguins |> 
  datatable(extensions = "Buttons", 
            # each letter Blfrtip associated with piece of table, B = buttons, 
            # p = pagination, l = length t = table. if delete a letter removes from table. 
            options = list (dom = "Blfrtip",
                            buttons = c("copy", "csv", "excel", "pdf", "print")
                            )
            ) 
```

New Page {data-navmenu="Pages"}
========================================================================

This is a placeholder. 
